config/routes.rb
SkyHopper::Application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  resources :zabbix_servers
  resources :users_admin, except: :show do
    collection do
      put 'sync_zabbix'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  root to: 'root#root'

  resources :clients, except: :show

  resources :projects, except: :show
  resource :project_parameters, only: [:show, :update]

  resources :key_pairs, only: [:index, :destroy], param: :fingerprint do
    collection do
      get  'retrieve'
    end
  end

  resources :snapshots, only: [:index, :create, :destroy], param: :snapshot_id do
    collection do
      post 'schedule'
      post 'save_retention_policy'
    end
  end

  resources :infrastructures do
    member do
      post 'change_rds_scale'
      post 'rds_submit_groups'
      get  'show_rds'
      get  'show_elb'
      get  'show_s3'
      get  'stack_events'
      get  'get_schedule'
      post 'delete_stack'
      post 'save_schedule'
    end
  end

  resources :ec2_private_keys, only: [:create]

  resources :resources, only: [:index, :create]

  resources :nodes, only: [:update, :show, :edit] do
    collection do
      get  'recipes'
      post 'create_group'
    end
    member do
      put  'cook'
      put  'yum_update'
      get  'run_bootstrap'
      post 'apply_dish'
      post 'submit_groups'
      put  'update_attributes'
      get  'edit_attributes'
      get  'get_rules'
      get  'get_security_groups'
      post 'schedule_yum'
    end
  end

  resources :ec2_instances, only: [] do
    member do
      post 'change_scale'
      post 'start'
      post 'stop'
      post 'reboot'
      post 'detach'
      post 'terminate'
      get  'serverspec_status'
      post 'register_to_elb'
      post 'deregister_from_elb'
      post 'elb_submit_groups'
      get  'attachable_volumes'
      get  'available_resources'
      post 'attach_volume'
      post 'detach_volume'
    end
    collection do
      post 'create_volume'
    end
  end

  resources :elb, only: [] do
    collection do
      post 'create_listener'
      post 'delete_listener'
      post 'update_listener'
      post 'upload_server_certificate'
      post 'delete_server_certificate'
    end
  end

  resources :serverspecs do
    collection do
      get  'select'
      get  'results'
      post 'run'
      put  'create_for_rds'
      post 'schedule'
      get  'generator'
    end
  end

  resources :infrastructure_logs, only: :index

  resources :monitorings, only: [:create, :show, :edit, :update] do
    member do
      post 'create_host'
      post 'update_templates'
      get 'show_cloudwatch_graph'
      get 'show_problems'
      get 'show_url_status'
    end

    collection do
      get 'show_zabbix_graph'
    end
  end

  resources :cf_templates do
    collection do
      post 'throwjson'
      post 'add_ebs'
      post 'insert_cf_params'
      get  'history'
      get  'new_for_creating_stack'
      post 'create_and_send'
    end
  end

  resources :template_builder, only: [:create, :new] do
    collection do
      get 'resource_properties'
    end
  end

  resources :dishes do
    member do
      post 'validate'
      get  'runlist'
    end
  end

  resource :app_settings, only: [:create, :show] do
    collection do
      get :project
      get :system
      get :chef

      post :project_update

      get  :chef_new
      post :chef_create
      get  :chef_server
      get  :chef_keys

      get  :db
      get  :export_db

      get  :edit_zabbix
      post :update_zabbix
      post :generate_key
    end
  end

  resources :server_status, param: :kind, only: [] do
    member do
      post :start
      post :stop
      post :status
    end
  end
end

app/controllers/infrastructures_controller.rb
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013-2016 SKYARCH NETWORKS INC.
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#

class InfrastructuresController < ApplicationController
  include Concerns::InfraLogger

  # --------------- Auth
  before_action :authenticate_user!

  # --------------- existence check
  before_action :project_exist, only: [:index]
  before_action :infrastructure_exist, only: [:show, :edit, :update, :destroy, :delete_stack, :stack_events]


  before_action :set_infrastructure, only: [:show, :edit, :update, :destroy, :delete_stack, :stack_events, :show_rds, :show_elb]

  before_action do
    infra = @infrastructure || (
      project_id = params[:project_id] || params[:infrastructure][:project_id] rescue nil
      Infrastructure.new(project_id: project_id)
    )

    authorize(infra)
  end


  before_action :with_zabbix, only: [:destroy, :delete_stack]

  @@regions = AWS::Regions



  # GET /infrastructures
  # GET /infrastructures.json
  def index
    project_id = params.require(:project_id)
    session[:project_id] = project_id
    page       = params[:page] || 1

    @selected_project = Project.find(project_id)

    @infrastructures = @selected_project.infrastructures.includes(:ec2_private_key).page(page)
    @selected_client = @selected_project.client

    respond_to do |format|
      format.json
      format.html
    end
  end

  # GET /infrastructures/:id
  def show
    stack = Stack.new(@infrastructure)

    resp = {
      status:        stack.status_and_type,
      name:          @infrastructure.stack_name,
      token_invalid: stack.status[:message].eql?("The security token included in the request is invalid."),
    }

    # When stack does not exist
    unless stack.status[:available] # in many cases, it will be when stack does not exist.
      @infrastructure.status = ""
      @infrastructure.save!
      @infrastructure.resources.destroy_all

      resp[:message] = stack.status[:message]
    end

    if stack.update_complete?
      @infrastructure.resources.destroy_all
    end

    @infrastructure.status = stack.status[:status]
    @infrastructure.save!

    render json: resp and return
  end

  # GET /infrastructures/:id/stack_events
  def stack_events
    stack = Stack.new(@infrastructure)
    events = nil
    begin
      events = stack.events
      # rubocop:disable Lint/HandleExceptions
    rescue Aws::CloudFormation::Errors::ValidationError # stack does not exist
      # rubocop:enable Lint/HandleExceptions
    end

    render json: {
      stack_status: stack.status_and_type,
      stack_events: events,
    } and return
  end

  # GET /infrastructures/new
  def new
    project_id = params.require(:project_id)
    @infrastructure = Infrastructure.new(
      project_id: project_id
    )
    @regions = @@regions
  end

  # GET /infrastructures/1/edit
  # スタック情報が取得できない場合のみ
  def edit
    if @infrastructure.status.present?
      redirect_to infrastructures_path(project_id: @infrastructure.project_id),
        alert: I18n.t('infrastructures.msg.not_necessary')
    end

    @regions = @@regions
  end

  # POST /infrastructures
  # POST /infrastructures.json
  def create
    keypair_validation
    infra = Infrastructure.create_with_ec2_private_key!(infrastructure_params)
  rescue => ex
    flash[:alert] = ex.message
    @regions        = @@regions
    @infrastructure = Infrastructure.new(infrastructure_params(no_keypair: true))

    render action: 'new', status: 400 and return
  else
    redirect_to infrastructures_path(project_id: infra.project_id),
      notice: I18n.t('infrastructures.msg.created')
  end

  # PATCH/PUT /infrastructures/1
  # PATCH/PUT /infrastructures/1.json
  def update
    begin
      @infrastructure.update!(infrastructure_params)
    rescue => ex
      @regions = @@regions
      flash[:alert] = ex.message
      render action: :edit, status: 400 and return
    end

    redirect_to infrastructures_path(project_id: @infrastructure.project_id),
      notice: I18n.t('infrastructures.msg.updated')
  end

  # DELETE /infrastructures/1
  # DELETE /infrastructures/1.json
  ## detach
  def destroy
    @infrastructure.destroy!

    render text: I18n.t('infrastructures.msg.detached')
  end

  # POST /infrastructures/1/delete_stack
  def delete_stack
    @infrastructure.detach_zabbix
    @infrastructure.detach_chef

    begin
      stack = Stack.new(@infrastructure)
      stack.delete # it returns nil without exception if there is no stack in the region
    rescue => ex
      logger.error "#{ex.class}: #{ex.message.inspect}"
      logger.error ex.backtrace.join("\n")
      @infrastructure.status = stack.status[:status]
      @infrastructure.save!
      infra_logger_fail("Deleting stack is failed. \n #{ex.class}: #{ex.message.inspect} \n" + ex.backtrace.join("\n"))

      raise ex
    end

    infra_logger_success("Deleting stack is successfully started.")

    @infrastructure.resources.destroy_all
    @infrastructure.monitorings.delete_all

    render text: I18n.t('infrastructures.msg.delete_stack_started'), status: 202 and return
  end

  # GET /infrastructures/:id/show_rds
  def show_rds
    physical_id = params.require(:physical_id)
    sc_g = @infrastructure.ec2.describe_security_groups.to_h
    rds = RDS.new(@infrastructure, physical_id)
    security_groups = map_security_groups(sc_g, rds.security_groups)

    @rds             = rds
    @security_groups = security_groups
  end

  # GET /infrastructures/:id/show_elb
  def show_elb
    physical_id = params.require(:physical_id)

    elb = ELB.new(@infrastructure, physical_id)

    sc_g = @infrastructure.ec2.describe_security_groups().to_h
    security_groups = map_security_groups(sc_g, elb.security_groups)


    @ec2_instances = elb.instances
    @dns_name      = elb.dns_name
    @listeners     = elb.listeners

    @security_groups = security_groups

    ec2 = @infrastructure.resources.ec2
    @unregistereds = ec2.reject{|e| @ec2_instances.map{|x|x[:instance_id]}.include?(e.physical_id)}

    list_server_certificates = elb.list_server_certificates

    @server_certificate_name_items = list_server_certificates[0].reject{|crt| crt.nil?}.map do |crt|
      {
        text: crt['server_certificate_name'],
        value: crt['arn'],
      }
    end

    @server_certificates = list_server_certificates[0].reject{|crt| crt.nil?}.map do |crt|
      {
        name: crt['server_certificate_name'],
        expiration: crt['expiration'],
      }
    end
  end

  # POST /infrastructures/change_rds_scale
  def change_rds_scale
    physical_id = params.require(:physical_id)
    infra_id    = params.require(:id)
    type        = params.require(:instance_type)

    rds = Infrastructure.find(infra_id).rds(physical_id)

    before_type = rds.db_instance_class

    begin
      changed_type = rds.change_scale(type)
    rescue RDS::ChangeScaleError => ex
      render text: ex.message, status: 400 and return
    end

    if before_type == changed_type
      render text: "There is not change '#{type}'", status: 200 and return
    end


    # TODO: status を取得
    render text: "change scale to #{type}" and return
  end

  # POST /infreastructures/rds_submit_groups
  def rds_submit_groups
    physical_id = params.require(:physical_id)
    infra_id    = params.require(:id)
    group_ids   = params.require(:group_ids)

    rds = Infrastructure.find(infra_id).rds(physical_id)
    rds.modify_security_groups(group_ids)

    infra_logger_success("#{physical_id} security groups has been modified.")

    render text: I18n.t('security_groups.msg.change_success')
  end

  def show_s3
    @bucket_name = params.require(:bucket_name)
    infra_id     = params.require(:id)

    infrastructure = Infrastructure.find(infra_id)
    @s3 = S3.new(infrastructure, @bucket_name)

    render partial: 'show_s3'
  end


  # GET /infreastructures/get_schedule
  # @param [Integer] infra_id
  # @param [String]  physical_id
  def get_schedule
    infra_id = params.require(:infra_id)
    physical_id = params.require(:physical_id)
    resource = Resource.where(infrastructure_id: infra_id).find_by(physical_id: physical_id)

    @operation_schedule = resource.operation_durations.order("created_at desc")

    respond_to do |format|
      format.json { render json: @operation_schedule.as_json(only: [:id, :start_date, :end_date],
        include: [{recurring_date: {only: [:id, :repeats, :start_time, :end_time, :dates]}},
                  {resource: {only: [:physical_id]}} ])
      }
    end
  end

  # POST /infrastructures/save_schedule
  # @param [Integer] infra_id
  # @param [String] physical_id
  # @param [Object] selected_instance
  def save_schedule
    selected_instance =  params.require(:selected_instance)
    ops_exists = OperationDuration.find_by(resource_id: selected_instance[:id])
    start_date = Time.at(selected_instance[:start_date].to_i).in_time_zone
    end_date = Time.at(selected_instance[:end_date].to_i).in_time_zone

    if ops_exists
      ops_exists.start_date = start_date
      ops_exists.end_date =  end_date
      ops_exists.save

      recur_exits = RecurringDate.find_by(operation_duration_id: ops_exists.id)
      recur_exits.repeats = selected_instance[:repeat_freq].to_i
      recur_exits.start_time = start_date.strftime("%H:%M")
      recur_exits.end_time = end_date.strftime("%H:%M")
      recur_exits.dates = selected_instance[:dates]
      recur_exits.save
    else
      begin
        ops = OperationDuration.create!(
          resource_id:  selected_instance[:id],
          start_date:   start_date,
          end_date:     end_date,
          user_id: current_user.id
        )
        RecurringDate.create!(
          operation_duration_id: ops.id,
          repeats: selected_instance[:repeat_freq].to_i,
          start_time:  start_date.strftime("%H:%M"),
          end_time: end_date.strftime("%H:%M"),
          dates: selected_instance[:dates]
        )
      rescue => ex

app/helpers/infrastructures_helper.rb
#
# Copyright (c) 2013-2016 SKYARCH NETWORKS INC.
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#

module InfrastructuresHelper
  def edit_infra(infra, user: current_user)
    return nil unless Pundit.policy(user, infra).edit?

    editable = if infra.status.present?
                 nil
               else
                 edit_infrastructure_path(infra)
    end

    return editable

  end

  def button_detach_stack(infra, user: current_user)
    return nil unless Pundit.policy(user, infra).destroy?

    if deleting?(infra.status)
      return nil
    end

    return true

  end

  def button_delete_stack(infra, user: current_user)
    return nil unless Pundit.policy(user, infra).delete_stack?
    deletable =  deleting?(infra.status) || infra.status.blank? ? nil : true
    return deletable
  end

  def button_add_infra(project, user: current_user)
    return nil unless Pundit.policy(user, Infrastructure.new(project: project)).new?

    link_to t('infrastructures.btn.add'),
      new_infrastructure_path(project_id: project.id),
      class: 'btn btn-primary btn-sm'
  end

  def project_params_usage
    <<-EOS.html_safe
<div class="bs-callout bs-callout-info">
  #{t('project_parameters.usage')}
</div>
    EOS
  end


  private

  def deleting?(status)
    return false unless status
    return false if status == "DELETE_FAILED"

    status.include?("DELETE")
  end
end

app/views/infrastructures/_form.html.erb
<%= form_for @infrastructure, html: { class: 'form-horizontal', multipart: true, role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :project_name, t('projects.project'), class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_field :project_name, value: @infrastructure.project.name, class: 'form-control', readonly: true %>
      <%= f.hidden_field :project_id %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :stack_name, t('infrastructures.stackname'), class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_field :stack_name, class: 'form-control', required: true, pattern: '[a-zA-Z][a-zA-Z0-9-]*', maxlength: 128 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :region, t('infrastructures.region'), class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.select :region, @regions, {}, {class: "form-control"} %>
    </div>
  </div>


  <div class="form-group">
    <label class="col-sm-2 control-label"><%= t 'app_settings.aws_keypair' %></label>
    <div class="col-sm-5">
<% if controller.action_name == "edit" ||  controller.action_name == "update" %>
      <%= f.text_field :key_name, value: @infrastructure.ec2_private_key.name, class: 'form-control', readonly: true if @infrastructure.ec2_private_key_id %>
      <%= uneditable_input(t('infrastructures.msg.no_keypair')) unless @infrastructure.ec2_private_key_id %>
<% else %>
      <p class="help-block"><%= t('ec2_private_keys.msg.enter_or_generate') %></p>
      <p><button class="btn btn-default btn-sm create_ec2_key"><%= t 'ec2_private_keys.btn.new' %></button></p>
      <label for="keypair_name" class="control-label"><%= t 'app_settings.keypair_name' %></label>
      <input id="keypair_name" class="form-control ec2-private-key-name allow-empty" type="text" name="infrastructure[keypair_name]" required maxlength="255">

      <label for="keypair_value" class="control-label"><%= t 'app_settings.private_key' %></label>
      <textarea id="keypair_value" class="form-control ec2-private-key-value allow-empty" name="infrastructure[keypair_value]" placeholder="<%= t 'common.msg.key_droppable' %>" rows="7" required></textarea>
      <p class="help-block"><%= t('infrastructures.msg.help_keypair') %></p>
<% end %>
    </div>
  </div>


  <div class="form-actions-top">
    <%= f.submit nil, class: 'btn btn-primary create' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
      infrastructures_path(project_id: @infrastructure.project_id),
      class: 'btn btn-default' %>
  </div>
<% end %>

app/views/infrastructures/_resource_tabs.html.erb
<!-- resources TABs -->
<%# TODO: DRY %>
<li v-for="ec2 in current_infra.resources.ec2_instances" :class="{active: tabpaneGroupID === ec2.physical_id}" @click="show_ec2(ec2.physical_id)">
  <a href="#">
    <span class="label label-warning"><%= fa 'cube' %> EC2</span>&nbsp;
    <small>{{screen_name(ec2)}}</small>
    <small v-if="tabpane_active(ec2.physical_id)"><%= glyphicon 'refresh' %></small>
    <!-- workaround http://stackoverflow.com/questions/18730116/twitter-bootstrap-3-0-how-do-i-badge-badge-important-now -->
    <bootstrap-tooltip v-if="!ec2.serverspec_status" :title="serverspec_failed" class="badge progress-bar-danger">
      <template slot="content"><%= fa 'exclamation' %></template>
    </bootstrap-tooltip>
  </a>
</li>

<li v-for="rds in current_infra.resources.rds_instances" :class="{active: tabpaneGroupID === rds.physical_id}" @click="show_rds(rds.physical_id)">
  <a href="#">
    <span class="label label-info"><%= fa 'database' %> RDS</span>&nbsp;
    <small>{{screen_name(rds)}}</small>
    <small v-if="tabpane_active(rds.physical_id)"><%= glyphicon 'refresh' %></small>
  </a>
</li>

<li v-for="elb in current_infra.resources.elb_instances" :class="{active: tabpaneGroupID === elb.physical_id}" @click="show_elb(elb.physical_id)">
  <a href="#">
    <span class="label label-warning"> <%= fa 'balance-scale' %> ELB</span>&nbsp;
    <small>{{screen_name(elb)}}</small>
    <small v-if="tabpane_active(elb.physical_id)"><%= glyphicon 'refresh' %></small>
  </a>
</li>

<li v-for="s3 in current_infra.resources.s3_buckets" :class="{active: tabpaneGroupID === s3.physical_id}" @click="show_s3(s3.physical_id)">
  <a href="#">
    <span class="label label-danger">S3</span>&nbsp;
    <small>{{screen_name(s3)}}</small>&nbsp;
    <small v-if="tabpane_active(s3.physical_id)"><%= glyphicon 'refresh' %></small>
  </a>
</li>

app/views/infrastructures/_show_s3.erb
<h4 class="page-header"><%= @bucket_name %></h4>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= t 'infrastructures.genre' %></th>
      <th><%= t 'common.value' %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Owner</td>
      <td><%= @s3.owner %></td>
    </tr>
    <tr>
      <td>Bucket URL</td>
      <td><%= @s3.url %></td>
    </tr>
    <tr>
      <td>Website Configuration</td>
      <td><%= @s3.website? %></td>
    </tr>

    <% if @s3.website? %>
      <tr>
        <td>Website URL</td>
        <td><%= link_to(@s3.public_url, @s3.public_url, {target: "_blank"}) %></td>
      </tr>
      <tr>
        <td>Index Document</td>
        <td><%= @s3.index_document %></td>
      </tr>
      <tr>
        <td>Error Document</td>
        <td><%= @s3.error_document %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/infrastructures/edit.html.erb
<% provide(:title, I18n.t('infrastructures.infrastructure')+" | "+I18n.t('helpers.titles.edit')) %>
<%- model_class = Infrastructure -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/infrastructures/index.html.erb
<% provide(:title, I18n.t('infrastructures.infrastructure'))%>
<%- model_class = Infrastructure -%>
<div class="page-header">
  <h1><%=t 'infrastructures.infrastructure' %></h1>
  <%= breadcrumbs(@selected_client, @selected_project, nil) if current_user.master? %>
  <%= link_to t('infrastructures.return_to_projects'), projects_path, {class: "btn btn-small btn-link"} unless current_user.master? %>
</div>

<script id="grid-template" type="text/template"> <%= render 'vue/index' %> </script>

  <div id="indexElement" v-el:node>

    <div v-cloak>
      <div class="col-xs-4"><input type="text" class="form-control" v-model="searchQuery" placeholder="<%= t 'infrastructures.search' %>"></div>

      <div class="pull-right">
        <div class='btn-group'>
            <a class='btn btn-sm btn-danger disabled' data-toggle='dropdown' href='#' :class="{disabled: !can_delete()}">
              <%= fa 'trash' %> <%= t('infrastructures.btn.delete_stack') %>&nbsp;<span class='caret'></span>
            </a>
           <ul class='dropdown-menu'>
            <li>
             <a class='delete-stack' href='#' @click="delete_stack()">Execute</a>
          </li>
          </ul>
         </div>
      </div>

      <div class="pull-right">
        <div class="btn-group">
          <a class='btn btn-sm btn-warning disabled' href='#' @click="detach_infra()" :class="{disabled: !can_detach()}"><%= fa 'chain-broken' %> <%= t('helpers.links.detach') %></a>&nbsp
        </div>
      </div>

      <div class="pull-right">
        <div class="btn-group">
             <a class="btn btn-default btn-sm dropdown-toggle disabled" data-toggle="dropdown" href="#" :class="{disabled: !is_picked()}">
               <%= t 'common.btn.settings' %> <span class="caret"></span>
             </a>&nbsp
             <ul class="dropdown-menu">
               <li v-if="picked">
                 <a @click="show_sched()" href='#'> <%=  t('infrastructures.btn.operation_schedule') %></a>
                 <a :href='picked.serverspecs_path'>Serverspecs</a>
               </li>
             </ul>
        </div>
      </div>

      <div class="pull-right" v-cloak="picked">
        <a class="btn btn-default btn-sm disabled"
            :href="picked.edit_infrastructure_path" :class="{disabled: !can_edit()}">
            <span class='glyphicon glyphicon-edit'></span>
            <%= t 'helpers.links.edit' %>
        </a>&nbsp
      </div>
    </div>

    <demo-grid
    :data.sync="gridData"
    :columns="gridColumns"
    :filter-key="searchQuery"
    :picked.sync="picked"
    :index="index">
    </demo-grid>
  </div>

  <div  id="empty" style="display: none;"></div>
  <span id="loading"><div class="loader"></div> <%= t 'common.msg.loading' %></span>
  <hr>


<%= button_add_infra(@selected_project) %>

<div class="page-header"></div>

<%= render 'show' %>

app/views/infrastructures/new.html.erb
<% provide(:title, I18n.t('infrastructures.infrastructure')+" | "+I18n.t('helpers.titles.new')) %>
<%- model_class = Infrastructure -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>