config/routes.rb
SkyHopper::Application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  resources :zabbix_servers
  resources :users_admin, except: :show do
    collection do
      put 'sync_zabbix'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  root to: 'root#root'

  resources :clients, except: :show

  resources :projects, except: :show
  resource :project_parameters, only: [:show, :update]

  resources :key_pairs, only: [:index, :destroy], param: :fingerprint do
    collection do
      get  'retrieve'
    end
  end

  resources :snapshots, only: [:index, :create, :destroy], param: :snapshot_id do
    collection do
      post 'schedule'
      post 'save_retention_policy'
    end
  end

  resources :infrastructures do
    member do
      post 'change_rds_scale'
      post 'rds_submit_groups'
      get  'show_rds'
      get  'show_elb'
      get  'show_s3'
      get  'stack_events'
      get  'get_schedule'
      post 'delete_stack'
      post 'save_schedule'
    end
  end

  resources :ec2_private_keys, only: [:create]

  resources :resources, only: [:index, :create]

  resources :nodes, only: [:update, :show, :edit] do
    collection do
      get  'recipes'
      post 'create_group'
    end
    member do
      put  'cook'
      put  'yum_update'
      get  'run_bootstrap'
      post 'apply_dish'
      post 'submit_groups'
      put  'update_attributes'
      get  'edit_attributes'
      get  'get_rules'
      get  'get_security_groups'
      post 'schedule_yum'
    end
  end

  resources :ec2_instances, only: [] do
    member do
      post 'change_scale'
      post 'start'
      post 'stop'
      post 'reboot'
      post 'detach'
      post 'terminate'
      get  'serverspec_status'
      post 'register_to_elb'
      post 'deregister_from_elb'
      post 'elb_submit_groups'
      get  'attachable_volumes'
      get  'available_resources'
      post 'attach_volume'
      post 'detach_volume'
    end
    collection do
      post 'create_volume'
    end
  end

  resources :elb, only: [] do
    collection do
      post 'create_listener'
      post 'delete_listener'
      post 'update_listener'
      post 'upload_server_certificate'
      post 'delete_server_certificate'
    end
  end

  resources :serverspecs do
    collection do
      get  'select'
      get  'results'
      post 'run'
      put  'create_for_rds'
      post 'schedule'
      get  'generator'
    end
  end

  resources :infrastructure_logs, only: :index

  resources :monitorings, only: [:create, :show, :edit, :update] do
    member do
      post 'create_host'
      post 'update_templates'
      get 'show_cloudwatch_graph'
      get 'show_problems'
      get 'show_url_status'
    end

    collection do
      get 'show_zabbix_graph'
    end
  end

  resources :cf_templates do
    collection do
      post 'throwjson'
      post 'add_ebs'
      post 'insert_cf_params'
      get  'history'
      get  'new_for_creating_stack'
      post 'create_and_send'
    end
  end

  resources :template_builder, only: [:create, :new] do
    collection do
      get 'resource_properties'
    end
  end

  resources :dishes do
    member do
      post 'validate'
      get  'runlist'
    end
  end

  resource :app_settings, only: [:create, :show] do
    collection do
      get :project
      get :system
      get :chef

      post :project_update

      get  :chef_new
      post :chef_create
      get  :chef_server
      get  :chef_keys

      get  :db
      get  :export_db

      get  :edit_zabbix
      post :update_zabbix
      post :generate_key
    end
  end

  resources :server_status, param: :kind, only: [] do
    member do
      post :start
      post :stop
      post :status
    end
  end
end

app/controllers/users_admin_controller.rb
#
# Copyright (c) 2013-2016 SKYARCH NETWORKS INC.
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#

class UsersAdminController < ApplicationController
  include Concerns::InfraLogger

  before_action :authenticate_user!
  before_action do
    authorize User.new
  end

  before_action :with_zabbix, only: [:new, :create, :destroy, :edit, :update, :sync_zabbix]

  # user management
  # GET /users_admin
  def index
    page = params[:page] || 1

    @users = User.all.page(page)
    respond_to do |format|
      format.json
      format.html
    end
  end

  # register new user only by master
  # GET /users_admin/new
  def new
    @user = User.new(session[:form])
    session[:form] = nil  # remove temporary form data

    @zabbix_servers = ZabbixServer.all
  end

  # create new user only by master
  # POST /users_admin
  def create
    @user = User.new(
      email:                 params[:user][:email],
      password:              params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
      admin:                 params[:user][:admin],
      master:                params[:user][:master]
    )

    e = -> (ex) {
      flash[:alert] = ex.message
      session[:form] = {
        email:  params[:user][:email],
        admin:  params[:user][:admin],
        master: params[:user][:master],
      }
      redirect_to(action: :new)
    }

    begin
      @user.save!
    rescue => ex
      e.(ex) and return
    end

    begin
      #TODO カレントユーザーでZabbixとコネクションを張れるようにする
      z_params = params[:user][:zabbix_servers]
      z_params.shift
      @user.zabbix_server_ids = z_params
      zab = ZabbixServer.find(z_params)
      zab.each do |s|
        z = Zabbix.new(s.fqdn, s.username, s.password)
        z.create_user(@user)
      end
    rescue => ex
      @user.destroy
      e.(ex) and return
    end

    flash[:notice] = I18n.t('users.msg.created')
    redirect_to(action: :index) and return
  end

  # GET /users_admin/1/edit
  def edit
    user = User.find(params.require(:id))
    @user = user.trim_password
    @clients = Client.all.map{|c|{value: c.id, text: c.name}}
    @allowed_projects = user.projects.includes(:client).map do |project|
      client_name = project.client.name
      {value: project.id, text: "#{client_name}/#{project.name}[#{project.code}]"}
    end
    @allowed_zabbix = user.zabbix_servers.map do |zabbix|
      {value: zabbix.id, text: zabbix.fqdn}
    end

    @mfa_key, @mfa_qrcode = user.new_mfa_key
  end

  # PUT /users_admin/1
  def update
    body = JSON.parse(params.require(:body), symbolize_names: true)
    user_id          = params.require(:id)
    allowed_projects = body[:allowed_projects]
    master           = body[:master]
    admin            = body[:admin]
    mfa_secret_key   = body[:mfa_secret_key]
    remove_mfa_key   = body[:remove_mfa_key]
    password         = body[:password]
    password_confirm = body[:password_confirmation]
    allowed_zabbix   = body[:allowed_zabbix]

    user = User.find(user_id)
    if master
      user.projects = []
    else
      user.project_ids = allowed_projects
    end

    user.master = master
    user.admin = admin

    if password && password_confirm
      user.password = password
      user.password_confirmation = password_confirm
      set_password = true
    end

    user.zabbix_server_ids = allowed_zabbix
    user.mfa_secret_key = mfa_secret_key if mfa_secret_key
    user.mfa_secret_key = nil            if remove_mfa_key

    user.save!

    # Zabbix update create user.
    servers = ZabbixServer.all
    begin
      servers.each do |s|
        z = Zabbix.new(s.fqdn, s.username, s.password)
        if allowed_zabbix.include? s.id
          update_user_zabbix(z, user, set_password)
        elsif z.user_exists?(user.email)
          z.delete_user(user.email)
        end
      end
    rescue => ex
      flash[:alert] = I18n.t('users.msg.error', msg: ex.message)
      raise
    end

    render text: I18n.t('users.msg.updated')
  end

  # PUT /users_admin/sync_zabbix
  # 全てのユーザーをZabbixに登録する。
  def sync_zabbix
    servers = ZabbixServer.all
    servers.each do |s|
      z = Zabbix.new(s.fqdn, s.username, s.password)
      add_create_user(z)
    end

    render text: I18n.t('users.msg.synced'); return
  end

  # delete acount
  # DELETE /users_admin/1
  def destroy
    @user = User.find(params.require(:id))
    # delete user from zabbix
    servers = ZabbixServer.all
    begin
      servers.each do |s|
        z = Zabbix.new(s.fqdn, current_user.email, current_user.encrypted_password)
        z.delete_user(@user.email)
      end
    rescue => ex
      flash[:alert] = I18n.t('users.msg.error', msg: ex.message)
      raise
    end

    #delete user from SkyHopper
    @user.destroy

    ws_send(t('users.msg.deleted', name: @user.email), true)
    redirect_to(action: :index)
  end

  private

  def set_zabbix(fqdn)
    begin
      @zabbix = Zabbix.new(fqdn, current_user.email, current_user.encrypted_password)
    rescue => ex
      flash[:alert] = I18n.t('users.msg.error', msg: ex.message)
      redirect_to users_admin_index_path
    end
  end

  def add_create_user(zabbix)
    users = User.all
    users.each do |user|
      next if zabbix.user_exists?(user.email)

      zabbix.create_user(user)
    end
  end

  def update_user_zabbix(z, user, set_password)
    z.create_user(user) unless z.user_exists?(user.email)
    zabbix_user_id = z.get_user_id(user.email)

    if set_password
      z.update_user(zabbix_user_id, password: user.encrypted_password)
    end

    usergroup_ids = [z.get_group_id_by_user(user)]
    if user.master
      z.update_user(zabbix_user_id, usergroup_ids: usergroup_ids, type: z.get_user_type_by_user(user))
    else
      hostgroup_names = user.projects.pluck(:code).map{|code| code + (user.admin? ? '-read-write' : '-read')}
      if hostgroup_names.present?
        usergroup_ids.concat(z.get_usergroup_ids(hostgroup_names))
      end
      z.update_user(zabbix_user_id, usergroup_ids: usergroup_ids)
    end
  end

end

app/views/users_admin/_edit.html.erb
<h3 class="page-header"><%= t('users.edit') %></h3>

<div class="col-md-12 col-sm-12">
  <div class="col-md-2 col-sm-2">
    <h5 class="page-header"><%= t('users.role') %></h5>
    <div class="checkbox">
      <label>
        <input type="checkbox" v-model="user.master"><%= master_label %>
      </label>
    </div>
    <div class="checkbox">
      <label>
        <input type="checkbox" v-model="user.admin"><%= admin_label %>
      </label>
    </div>
  </div>

  <div class="col-sm-6 col-md-6">
    <h5 class="page-header"><%=t('users.change_password')%></h5>
    <form class="form-horizontal">
      <div class="form-group">
        <label for="password" class="col-sm-3 control-label"><%=t('users.password')%></label>
        <div class="col-sm-9">
          <input type="password" class="form-control input-sm" placeholder="Enter new password if you want to change" autocomplete="off" v-model="user.password">
        </div>
      </div>
      <div class="form-group">
        <label for="password_confirm" class="col-sm-3 control-label"><%=t('users.password_confirm')%></label>
        <div class="col-sm-9">
          <input type="password" class="form-control input-sm" v-model="user.password_confirmation" autocomplete="off">
        </div>
      </div>
    </form>
  </div>

  <div class="col-sm-4 col-md-4">
    <h5 class="page-header"><%=t('users.mfa')%></h5>
    <div v-if="user.mfa_use">
      <p><%=t('users.msg.mfa_used')%></p>
      <button class="btn btn-sm btn-default" @click="update_mfa()" :disabled="update_mfa_key || remove_mfa_key"><%=t('users.change_mfa_secret')%></button>
      <button class="btn btn-sm btn-danger"  @click="remove_mfa()" :disabled="update_mfa_key || remove_mfa_key"><%=t('users.use_stop_mfa')%></button>
    </div>
    <div v-else>
      <button class="btn btn-sm btn-primary" @click="update_mfa()"><%=t('users.use_start_mfa')%></button>
    </div>

    <div v-if="update_mfa_key">
      <p><%=t('users.mfa_secret')%>: <code>{{mfa_key}}</code></p>
      <div class="QRCode">
        {{{mfa_qrcode}}}
      </div>
      <p><%=t('users.msg.mfa_start_description')%></p>
    </div>

    <div v-if="remove_mfa_key">
      <div class="alert alert-danger" role="alert"><%=t('users.msg.use_stop_mfa')%></div>
    </div>
  </div>
</div>


<div class="col-md-7 col-sm-7">
  <div class="col-md-5 col-sm-5 form-group">
    <h5 class="page-header"><%= t('clients.client') %></h5>
    <select size="2" v-model="selected_client" number class="form-control admin-selectbox-height" @click="get_projects()">
      <option v-for="o in clients" :value="o.value">{{o.text}}</option>
    </select>
  </div>
  <div class="col-sm-7 col-md-7 form-group">
    <h5 class="page-header"><%= t('projects.project') %></h5>
    <select multiple="multiple" v-model="selected_projects" number class="form-control admin-selectbox-height" @dblclick="add()">
      <option v-for="o in projects" :value="o.value">{{o.text}}</option>
    </select>
  </div>
  <div class="col-sm-12 col-md-12">
    <div class="form-group">
      <button class="btn btn-default pull-right" @click="add()">
        <span class="glyphicon glyphicon-plus"></span>
      </button>
    </div>
  </div>
</div>


<div class="col-md-5 col-sm-5">
  <div class="col-md-12 col-sm-12">
    <h5 class="page-header"><%= t('users.allowed_projects') %></h5>

    <div class="col-sm-12 col-md-12">
      <div class="form-group">
        <select multiple="multiple" class="form-control admin-selectbox-height" v-model="selected_allowed_projects" number @dblclick="del()">
          <option v-for="o in allowed_projects" :value="o.value">{{o.text}}</option>
        </select>
      </div>
    </div>

    <div class="col-sm-12 col-md-12">
      <div class="form-group">
        <button class="btn btn-default" @click="del()">
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </div>
    </div>
  </div>
</div>

<div class="col-md-6 col-sm-6">
  <div class="col-md-12 col-sm-12 form-group">
    <h5 class="page-header">Zabbix Servers List</h5>
    <select multiple="multiple" size="2" v-model="selected_zabbix" number class="form-control admin-selectbox-height" @dblclick="add_zabbix()">
      <option v-for="z in zabbix_servers" :value="z.value">{{z.text}}</option>
    </select>
  </div>
  <div class="col-md-12 col-sm-12">
    <div class="form-group">
      <button class="btn btn-default pull-right" @click="add_zabbix()">
        <span class="glyphicon glyphicon-plus"></span>
      </button>
    </div>
  </div>
</div>

<div class="col-md-6 col-sm-6">
  <div class="col-md-12 col-sm-12">
    <h5 class="page-header">Selected Zabbix Servers</h5>

    <div class="col-sm-12 col-md-12">
      <div class="form-group">
        <select multiple="multiple" class="form-control admin-selectbox-height" v-model="selected_allowed_zabbix" number @dblclick="del_zabbix()">
          <option v-for="z in allowed_zabbix" :value="z.value">{{z.text}}</option>
        </select>
      </div>
    </div>

    <div class="col-sm-12 col-md-12">
      <div class="form-group">
        <button class="btn btn-default" @click="del_zabbix()">
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </div>
    </div>
  </div>
</div>

<div class="col-md-12 col-sm-12">
  <div class="form-actions-top">
    <button class="btn btn-primary btn-sm" @click="submit()">
      <%= t('common.btn.save_changes') %>
    </button>
  </div>
</div>

app/views/users_admin/index.html.erb
<% provide(:title, I18n.t('users.title')) %>
<div class="page-header">
  <h1><%= t('users.title')%></h1>
</div>

<script id="grid-template" type="text/template"> <%= render 'vue/index' %> </script>

<div id="indexElement">
  <div class="input-group">
    <input type="text" name="query" v-model="searchQuery" debounce="500" class="form-control" placeholder="<%= t 'users.search' %>">
    <hr>
  </div>


      <div class="pull-right" v-cloak="picked">
        <a class="btn btn-danger btn-sm disabled"
        @click="delete_entry()"
          :class="{disabled: can_delete()}">
            <%= fa 'times' %>
            <%= t 'common.btn.delete' %>
        </a>&nbsp
      </div>

      <div class="pull-right" v-cloak="picked">
        <a class="btn btn-default btn-sm edit-user"
            href="#" user-id="{{picked.id}}" :class="{disabled: can_edit()}">
            <span class='glyphicon glyphicon-edit'></span>
            <%= t 'helpers.links.edit' %>
        </a>&nbsp
      </div>

  <demo-grid
    :data.sync="gridData"
    :columns="gridColumns"
    :filter-key="searchQuery"
    :picked.sync="picked"
    :index="index">
  </demo-grid>
</div>

<div id="empty" style="display: none;"></div>
<span id="loading"><div class="loader"></div> <%= t 'common.msg.loading' %></span>
<hr>

<%= link_to new_users_admin_path, class: "btn btn-primary btn-sm" do %>
  <span class="fa fa-user-plus"></span> <%= t('users.btn.add') %>
<% end %>

<button class="btn btn-sm btn-default" id="sync_zabbix"><%= glyphicon("refresh") %> <%= t('users.btn.sync') %></button>

<div class="page-header"></div>
<div id="user-edit" style="padding-bottom: 70px;"></div>

<script id="user-edit-template" type="text/template">
<%= render 'edit' %>
</script>

app/views/users_admin/new.html.erb
<% provide(:title, I18n.t('users.create_new_user')) %>
<div class="page-header">
  <h1><%= t('users.create_new_user') %></h1>
</div>
<%= form_for @user, url: {action: 'create'}, html: {class: "form-horizontal", role: "form"} do |f| %>

  <div class="form-group">
    <%= f.label t('users.email'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.email_field :email, autofocus: true, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label t('users.password'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.password_field :password, class: "form-control", required: true, pattern: '[^\s]+' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label t('users.password_confirm'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.password_field :password_confirmation, class: "form-control", required: true, pattern: '[^\s]+' %>
    </div>
  </div>

  <div class="form-group">
    <div class="checkbox col-sm-offset-2 col-sm-1">
      <%= f.label :admin, f.check_box(:admin) + admin_label, {class: "col-sm-2"} %>
    </div>
    <div class="checkbox col-sm-2">
      <%= f.label :master, f.check_box(:master) + master_label, {class: "col-sm-2"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label t('zabbix_servers.zabbix'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= f.select(:zabbix_servers, options_from_collection_for_select(@zabbix_servers, 'id', 'fqdn'), {}, {:multiple => true, :size => 10, :required => true}) %>
    </div>
  </div>



  <div class="form-actions-top">
    <%= f.submit t('helpers.links.create'), class: "btn btn-primary create" %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
      users_admin_index_path,
      class: 'btn btn-default' %>
  </div>
<% end %>