config/routes.rb
SkyHopper::Application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  resources :zabbix_servers
  resources :users_admin, except: :show do
    collection do
      put 'sync_zabbix'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  root to: 'root#root'

  resources :clients, except: :show

  resources :projects, except: :show
  resource :project_parameters, only: [:show, :update]

  resources :key_pairs, only: [:index, :destroy], param: :fingerprint do
    collection do
      get  'retrieve'
    end
  end

  resources :snapshots, only: [:index, :create, :destroy], param: :snapshot_id do
    collection do
      post 'schedule'
      post 'save_retention_policy'
    end
  end

  resources :infrastructures do
    member do
      post 'change_rds_scale'
      post 'rds_submit_groups'
      get  'show_rds'
      get  'show_elb'
      get  'show_s3'
      get  'stack_events'
      get  'get_schedule'
      post 'delete_stack'
      post 'save_schedule'
    end
  end

  resources :ec2_private_keys, only: [:create]

  resources :resources, only: [:index, :create]

  resources :nodes, only: [:update, :show, :edit] do
    collection do
      get  'recipes'
      post 'create_group'
    end
    member do
      put  'cook'
      put  'yum_update'
      get  'run_bootstrap'
      post 'apply_dish'
      post 'submit_groups'
      put  'update_attributes'
      get  'edit_attributes'
      get  'get_rules'
      get  'get_security_groups'
      post 'schedule_yum'
    end
  end

  resources :ec2_instances, only: [] do
    member do
      post 'change_scale'
      post 'start'
      post 'stop'
      post 'reboot'
      post 'detach'
      post 'terminate'
      get  'serverspec_status'
      post 'register_to_elb'
      post 'deregister_from_elb'
      post 'elb_submit_groups'
      get  'attachable_volumes'
      get  'available_resources'
      post 'attach_volume'
      post 'detach_volume'
    end
    collection do
      post 'create_volume'
    end
  end

  resources :elb, only: [] do
    collection do
      post 'create_listener'
      post 'delete_listener'
      post 'update_listener'
      post 'upload_server_certificate'
      post 'delete_server_certificate'
    end
  end

  resources :serverspecs do
    collection do
      get  'select'
      get  'results'
      post 'run'
      put  'create_for_rds'
      post 'schedule'
      get  'generator'
    end
  end

  resources :infrastructure_logs, only: :index

  resources :monitorings, only: [:create, :show, :edit, :update] do
    member do
      post 'create_host'
      post 'update_templates'
      get 'show_cloudwatch_graph'
      get 'show_problems'
      get 'show_url_status'
    end

    collection do
      get 'show_zabbix_graph'
    end
  end

  resources :cf_templates do
    collection do
      post 'throwjson'
      post 'add_ebs'
      post 'insert_cf_params'
      get  'history'
      get  'new_for_creating_stack'
      post 'create_and_send'
    end
  end

  resources :template_builder, only: [:create, :new] do
    collection do
      get 'resource_properties'
    end
  end

  resources :dishes do
    member do
      post 'validate'
      get  'runlist'
    end
  end

  resource :app_settings, only: [:create, :show] do
    collection do
      get :project
      get :system
      get :chef

      post :project_update

      get  :chef_new
      post :chef_create
      get  :chef_server
      get  :chef_keys

      get  :db
      get  :export_db

      get  :edit_zabbix
      post :update_zabbix
      post :generate_key
    end
  end

  resources :server_status, param: :kind, only: [] do
    member do
      post :start
      post :stop
      post :status
    end
  end
end

app/models/serverspec.rb
#
# Copyright (c) 2013-2016 SKYARCH NETWORKS INC.
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#

require 'fileutils'

class Serverspec < ActiveRecord::Base
  belongs_to :infrastructure

  has_many :dish_serverspecs
  has_many :dishes, through: :dish_serverspecs
  has_many :resource_serverspecs
  has_many :resources, through: :resource_serverspecs
  has_many :serverspec_results, through: :serverspec_result_details

  validates :value, ruby: true

  TmpDir = Rails.root.join('tmp', 'serverspec')
  FileUtils::mkdir_p(TmpDir) unless Dir::exist?(TmpDir)

  [:name, :value].each do |sym|
    validates sym, presence: true
  end

  class << self
    def for_infra(infrastructure_id)
      where(infrastructure_id: [nil, infrastructure_id]).to_a
    end

    def global
      where(infrastructure_id: nil)
    end

    def to_file(id)
      require 'tempfile'
      result = Tempfile.new(id.to_s, TmpDir)
      result.write(find_by(id: id).value)
      result.flush
      result.path
    end

    def create_rds(rds, user, passwd, infra_id, db_name = nil)
      require 'erb'

      db_engine = rds.engine_type
      db_engine = 'psql' if db_engine == 'postgres'
      host      = rds.endpoint_address

      spec_template = File::open(Rails.root.join('serverspec/rdsspec.rb.erb')).read

      spec_value = ERB.new(spec_template).result(binding)

      description = "Check connection to RDS host:#{host[/^([^\.]+)\./, 1]} as user:#{user}"
      description << ", database:#{db_name}" if db_name

      return self.create(
        infrastructure_id: infra_id,
        name:              "RDS connection to #{host[/^([^\.]+)\./, 1]}",
        value:             spec_value,
        description:       description
      )
    end
  end
end

app/controllers/serverspecs_controller.rb
#
# Copyright (c) 2013-2016 SKYARCH NETWORKS INC.
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#

class ServerspecsController < ApplicationController
  include Concerns::InfraLogger

  before_action :set_serverspec, only: [:update, :show, :edit, :destroy]

  # --------------- Auth
  before_action :authenticate_user!

  before_action do
    authorize(@serverspec || Serverspec.new(infrastructure_id: have_infra?))
  end

  # GET /serverspecs
  def index
    @infrastructure_id = params[:infrastructure_id]
    page               = params[:page]

    @infrastructure_name = Infrastructure.find(@infrastructure_id).stack_name if @infrastructure_id
    @serverspecs = Serverspec.where(infrastructure_id: @infrastructure_id).page(page)

    respond_to do |format|
      format.json
      format.html
    end
  end

  # GET /serverspecs/new
  def new
    infra_id = params[:infrastructure_id]

    @serverspec = Serverspec.new(infrastructure_id: infra_id)
    @serverspec.value = %!require 'serverspec_helper'\n\n!
  end

  # GET /serverspecs/1
  def show
    render text: @serverspec.value
  end

  # POST /serverspecs/1
  def update
    if @serverspec.update(global_serverspec_params)
      redirect_to serverspecs_path, notice: I18n.t('serverspecs.msg.updated')
    else
      flash.now[:alert] = @serverspec.errors[:value] if @serverspec.errors[:value]
      render action: 'edit'
    end
  end

  # POST /serverspecs
  def create
    @serverspec = Serverspec.new(global_serverspec_params)

    infra_id = @serverspec.infrastructure_id

    begin
      @serverspec.save!
    rescue => ex
      raise ex if ajax?
      flash.now[:alert] = @serverspec.errors[:value] if @serverspec.errors[:value]
      render action: 'new', infrastructure_id: infra_id; return
    end

    if ajax?
      render text: I18n.t('serverspecs.msg.created') and return
    else
      redirect_to serverspecs_path(infrastructure_id: infra_id),
        notice: I18n.t('serverspecs.msg.created')
    end
  end

  # GET /serverspecs/1/edit
  def edit
  end

  # GET /serverspecs/generator
  def generator
    @infra = Infrastructure.find(params[:infrastructure_id]) if params[:infrastructure_id]
  end

  # DELETE /serverspecs/1
  def destroy
    infra_id = @serverspec.infrastructure_id
    @serverspec.destroy

    redirect_to serverspecs_path(infrastructure_id: infra_id), notice: I18n.t('serverspecs.msg.deleted')
  end

  # GET /serverspecs/select
  def select
    physical_id = params.require(:physical_id)
    infra_id    = params.require(:infra_id)

    resource = Resource.where(infrastructure_id: infra_id).find_by(physical_id: physical_id)
    @selected_serverspec_ids = resource.all_serverspec_ids

    serverspecs = Serverspec.for_infra(infra_id)
    @individual_serverspecs, @global_serverspecs = serverspecs.partition{|spec| spec.infrastructure_id }
    node = Node.new(physical_id)
    @is_available_auto_generated = node.have_auto_generated

    @serverspec_schedule = ServerspecSchedule.find_or_create_by(physical_id: physical_id)
  end

  # GET /serverspecs/results
  def results
    physical_id = params.require(:physical_id)
    infra_id    = params.require(:infra_id)
    resource = Resource.where(infrastructure_id: infra_id).find_by(physical_id: physical_id)

    @serverspec_results = resource.serverspec_results.order("created_at desc")

    respond_to do |format|
      format.json { render json: @serverspec_results.as_json(only: [:id, :status, :message, :created_at],
        include: [{serverspec_result_details: {only: [:id]}},{serverspecs: {only:[:name]}}, {resource: {only: [:physical_id]}} ]) }
    end
  end


  # TODO: refactor
  # POST /serverspecs/run
  def run
    physical_id    = params.require(:physical_id)
    infra_id       = params.require(:infra_id)
    serverspec_ids = params.require(:serverspec_ids)
    resource = Resource.where(infrastructure_id: infra_id).find_by(physical_id: physical_id)
    if selected_auto_generated = serverspec_ids.include?('-1')
      serverspec_ids.delete('-1')
    end

    begin
      resp = ServerspecJob.perform_now(
        physical_id, infra_id, current_user.id,
        serverspec_ids: serverspec_ids, auto_generated: selected_auto_generated
      )
    rescue => ex
      # serverspec が正常に実行されなかったとき
      render text: ex.message, status: 500 and return
    end

    case resp[:status_text]
    when 'success'
      render_msg = I18n.t('serverspecs.msg.success', physical_id: physical_id)
    when 'pending'
      render_msg = I18n.t('serverspecs.msg.pending', physical_id: physical_id, pending_specs: resp[:short_msg])
    when 'failed'
      render_msg = I18n.t('serverspecs.msg.failure', physical_id: physical_id, failure_specs: resp[:short_msg])
    end

    ServerspecResult.create(
      resource_id:    resource.id,
      status:         resp[:status_text],
      message:        resp[:message],
      serverspec_ids: serverspec_ids
    )
    render text: render_msg, status: 200 and return
  end


  # Generate serverspec to connect to RDS instance
  # PUT /serverspecs/create_for_rds
  def create_for_rds
    infra_id    = params.require(:infra_id)
    physical_id = params.require(:physical_id)
    username    = params.require(:username)
    password    = params.require(:password)
    database    = params[:database]
    database = nil if database.blank?

    infra = Infrastructure.find(infra_id)
    rds = RDS.new(infra, physical_id)

    Serverspec.create_rds(rds, username, password, infra_id, database)

    render text: I18n.t('serverspecs.msg.generated'), status: 201 and return
  end

  # POST /serverspecs/schedule
  def schedule
    physical_id = params.require(:physical_id)
    infra_id    = params.require(:infra_id)
    schedule    = params.require(:schedule).permit(:enabled, :frequency, :day_of_week, :time)

    ss = ServerspecSchedule.find_by(physical_id: physical_id)
    ss.update_attributes!(schedule)

    if ss.enabled?
      PeriodicServerspecJob.set(
        wait_until: ss.next_run
      ).perform_later(physical_id, infra_id, current_user.id)
    end

    render text: I18n.t('schedules.msg.serverspec_updated'), status: 200 and return
  end


  private

  def set_serverspec
    @serverspec = Serverspec.find(params.require(:id))
  end

  def global_serverspec_params
    params.require(:serverspec).permit(:name, :description, :value, :infrastructure_id)
  end

  def have_infra?
    return params[:infra_id] || params[:infrastructure_id] || params[:serverspec][:infrastructure_id]
  rescue
    return nil
  end
end

app/views/serverspecs/_form.html.erb
<%= form_for @serverspec, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <% if @serverspec.infrastructure_id %>
    <div class="form-group">
      <%= f.label :infrastructure_id, t('infrastructures.infrastructure'), class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= uneditable_input(@serverspec.infrastructure.stack_name) %>
        <%= f.hidden_field :infrastructure_id %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, t('serverspecs.name'), class: 'control-label col-sm-2'%>
    <div class="col-sm-5">
      <%= f.text_field :name, class: 'form-control', required: true%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, t('serverspecs.description'), class: 'control-label col-sm-2'%>
    <div class="col-sm-5">
      <%= f.text_field :description, class: ' form-control text_field_no_validation'%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :value, t('serverspecs.value'), class: 'control-label col-sm-2'%>
    <div class="col-sm-5">
      <%= f.text_area :value, class: 'form-control', required: true%>
    </div>
  </div>

  <div class="form-actions-top">
    <%= f.submit t('common.btn.submit'), :class => 'btn btn-primary create'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      serverspecs_path(infrastructure_id: @serverspec.infrastructure_id), class: 'btn-default btn' %>
  </div>
<% end %>

app/views/serverspecs/edit.html.erb
<% provide(:title, I18n.t('serverspecs.serverspec')+" | "+I18n.t('helpers.titles.edit')) %>
<%- model_class = Serverspec -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/serverspecs/generator.html.erb
<% provide(:title, I18n.t('serverspecs.generator.title')) %>
<div class="container">
  <h2 class="page-header">
    <%=t('serverspecs.generator.title')%>
    <% if @infra %>
      <small><%= ('for ' + link_to(@infra.stack_name, infrastructures_path(project_id: @infra.project_id, infrastructure_id: @infra.id))).html_safe %></small>
    <% end %>
  </h2>

  <div id="vue-serverspec-gen"></div>

  <div class="row form-actions-top">
    <button class="btn btn-primary save-serverspec-btn"><%=t('helpers.titles.save')%></button>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      serverspecs_path(infrastructure_id: @infra.try(:id)), class: 'btn-default btn' %>
  </div>
</div>

app/views/serverspecs/index.html.erb
<% provide(:title, I18n.t('serverspecs.serverspec')) %>
<%- model_class = Serverspec -%>
<% allow_change = @infrastructure_id ? current_user.admin? : current_user.master? && current_user.admin? %>
<% project_id   = Infrastructure.find(@infrastructure_id).project_id if @infrastructure_id %>

<div class="page-header">
  <h1>
    <%= t('serverspecs.serverspec') %>&nbsp;
    <small><%= ('for ' + link_to(@infrastructure_name, infrastructures_path(project_id: project_id, infrastructure_id: @infrastructure_id))).html_safe if @infrastructure_name %></small>
  </h1>
</div>


<script id="grid-template" type="text/template"> <%= render 'vue/index' %> </script>

<div id="indexElement" v-el:node>

  <div v-cloak>
    <div class="col-xs-4"><input type="text" class="form-control" v-model="searchQuery" placeholder="<%= t 'infrastructures.search' %>"></div>

    <div class="pull-right">
      <a class="btn btn-danger btn-sm disabled"
      :class="{disabled: can_delete()}"
      @click="delete_entry()">
          <%= fa 'times' %>
          <%= t 'common.btn.delete' %>
      </a>&nbsp
    </div>

    <div class="pull-right" v-cloak="picked">
      <a class="btn btn-default btn-sm disabled"
          :href="picked.edit_serverspec_path" :class="{disabled: can_edit()}">
          <span class='glyphicon glyphicon-edit'></span>
          <%= t 'helpers.links.edit' %>
      </a>&nbsp
    </div>

  </div>


  <demo-grid
  :data.sync="gridData"
  :columns="gridColumns"
  :filter-key="searchQuery"
  :picked.sync="picked"
  :index="index">
  </demo-grid>
</div>


<% if allow_change %>
  <%= link_to t('.new', default: t('serverspecs.btn.add')),
    new_serverspec_path(infrastructure_id: @infrastructure_id),
    class: 'btn btn-primary btn-small' %>
  <%= link_to t('serverspecs.btn.generator'),
    generator_serverspecs_path(infrastructure_id: @infrastructure_id),
    class: 'btn btn-primary btn-small' %>
<% end %>

<div class="page-header"></div>

<div style='display:none; padding-bottom: 70px;' id='value'>
  <h5>Value</h5>
  <pre id='value-information'></pre>
</div>

<% content_for :sidebar do %><% end %>

app/views/serverspecs/new.html.erb
<% provide(:title, I18n.t('serverspecs.serverspec')+" | "+I18n.t('helpers.titles.new')) %>
<%- model_class = Serverspec -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>