config/routes.rb
SkyHopper::Application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  resources :zabbix_servers
  resources :users_admin, except: :show do
    collection do
      put 'sync_zabbix'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  root to: 'root#root'

  resources :clients, except: :show

  resources :projects, except: :show
  resource :project_parameters, only: [:show, :update]

  resources :key_pairs, only: [:index, :destroy], param: :fingerprint do
    collection do
      get  'retrieve'
    end
  end

  resources :snapshots, only: [:index, :create, :destroy], param: :snapshot_id do
    collection do
      post 'schedule'
      post 'save_retention_policy'
    end
  end

  resources :infrastructures do
    member do
      post 'change_rds_scale'
      post 'rds_submit_groups'
      get  'show_rds'
      get  'show_elb'
      get  'show_s3'
      get  'stack_events'
      get  'get_schedule'
      post 'delete_stack'
      post 'save_schedule'
    end
  end

  resources :ec2_private_keys, only: [:create]

  resources :resources, only: [:index, :create]

  resources :nodes, only: [:update, :show, :edit] do
    collection do
      get  'recipes'
      post 'create_group'
    end
    member do
      put  'cook'
      put  'yum_update'
      get  'run_bootstrap'
      post 'apply_dish'
      post 'submit_groups'
      put  'update_attributes'
      get  'edit_attributes'
      get  'get_rules'
      get  'get_security_groups'
      post 'schedule_yum'
    end
  end

  resources :ec2_instances, only: [] do
    member do
      post 'change_scale'
      post 'start'
      post 'stop'
      post 'reboot'
      post 'detach'
      post 'terminate'
      get  'serverspec_status'
      post 'register_to_elb'
      post 'deregister_from_elb'
      post 'elb_submit_groups'
      get  'attachable_volumes'
      get  'available_resources'
      post 'attach_volume'
      post 'detach_volume'
    end
    collection do
      post 'create_volume'
    end
  end

  resources :elb, only: [] do
    collection do
      post 'create_listener'
      post 'delete_listener'
      post 'update_listener'
      post 'upload_server_certificate'
      post 'delete_server_certificate'
    end
  end

  resources :serverspecs do
    collection do
      get  'select'
      get  'results'
      post 'run'
      put  'create_for_rds'
      post 'schedule'
      get  'generator'
    end
  end

  resources :infrastructure_logs, only: :index

  resources :monitorings, only: [:create, :show, :edit, :update] do
    member do
      post 'create_host'
      post 'update_templates'
      get 'show_cloudwatch_graph'
      get 'show_problems'
      get 'show_url_status'
    end

    collection do
      get 'show_zabbix_graph'
    end
  end

  resources :cf_templates do
    collection do
      post 'throwjson'
      post 'add_ebs'
      post 'insert_cf_params'
      get  'history'
      get  'new_for_creating_stack'
      post 'create_and_send'
    end
  end

  resources :template_builder, only: [:create, :new] do
    collection do
      get 'resource_properties'
    end
  end

  resources :dishes do
    member do
      post 'validate'
      get  'runlist'
    end
  end

  resource :app_settings, only: [:create, :show] do
    collection do
      get :project
      get :system
      get :chef

      post :project_update

      get  :chef_new
      post :chef_create
      get  :chef_server
      get  :chef_keys

      get  :db
      get  :export_db

      get  :edit_zabbix
      post :update_zabbix
      post :generate_key
    end
  end

  resources :server_status, param: :kind, only: [] do
    member do
      post :start
      post :stop
      post :status
    end
  end
end

app/models/zabbix_server.rb
class ZabbixServer < ActiveRecord::Base
  has_many :projects, dependent: :restrict_with_exception
  validates :fqdn, uniqueness: true, zabbix_server_fqdn: true

  has_many :user_zabbix_servers
  has_many :users, through: :user_zabbix_servers

  extend Concerns::Cryptize
  cryptize :password
end

app/controllers/zabbix_servers_controller.rb
class ZabbixServersController < ApplicationController
  include Concerns::InfraLogger
  # ------------- Auth
  before_action :authenticate_user!
  before_action :set_zabbix_server, only: [:show, :edit, :update, :destroy]

  # GET /zabbix_servers
  # GET /zabbix_servers.json
  def index
    @zabbix_servers = ZabbixServer.all

    respond_to do |format|
      format.json
      format.html
    end
  end

  # GET /zabbix_servers/1
  # GET /zabbix_servers/1.json
  def show
  end

  # GET /zabbix_servers/new
  def new
    @zabbix_server = ZabbixServer.new
  end

  # GET /zabbix_servers/1/edit
  def edit
  end

  # POST /zabbix_servers
  # POST /zabbix_servers.json
  def create
    params = zabbix_server_params
    begin
      z = Zabbix.new(params[:fqdn], params[:username], params[:password])
      params[:version] = z.version
    rescue => ex
      raise ex
    end

    @zabbix_server = ZabbixServer.new(params)

    respond_to do |format|
      if @zabbix_server.save
        format.html { redirect_to zabbix_servers_url, notice: I18n.t('zabbix_servers.msg.created') }
        format.json { render :show, status: :created, location: @zabbix_server }
      else
        format.html { render :new }
        format.json { render json: @zabbix_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zabbix_servers/1
  # PATCH/PUT /zabbix_servers/1.json
  def update
    respond_to do |format|
      if @zabbix_server.update(zabbix_server_params)
        format.html { redirect_to zabbix_servers_url, notice: I18n.t('zabbix_servers.msg.updated') }
        format.json { render :show, status: :ok, location: @zabbix_server }
      else
        format.html { render :edit }
        format.json { render json: @zabbix_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zabbix_servers/1
  # DELETE /zabbix_servers/1.json
  def destroy
    go = -> () { redirect_to zabbix_servers_url }
    begin
      @zabbix_server.destroy!
    rescue => ex
      flash[:alert] = ex.message
      go.() and return
    end

    ws_send(t('zabbix_servers.msg.deleted', name: @zabbix_server.fqdn), true)
    go.() and return
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_zabbix_server
    @zabbix_server = ZabbixServer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def zabbix_server_params
    params.require(:zabbix_server).permit(:fqdn, :username, :password, :version, :details)
  end

end

app/helpers/zabbix_servers_helper.rb
module ZabbixServersHelper
  def edit_zabbix_server_path_url(zabbix_server)
    return nil unless Pundit.policy(current_user, zabbix_server).edit?
    return edit_zabbix_server_path(zabbix_server)
  end

  def delete_zabbix_server_path(zabbix_server)
    return nil unless Pundit.policy(current_user, zabbix_server).destroy?
    # Exclude the default zabbix server from deletion
    return nil if zabbix_server.id == 1
    return zabbix_server_path(zabbix_server)
  end
end

app/views/zabbix_servers/_form.html.erb
<%= form_for @zabbix_server, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <% if @zabbix_server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zabbix_server.errors.count, "error") %> prohibited this zabbix_server from being saved:</h2>

      <ul>
      <% @zabbix_server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fqdn, class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <% if @zabbix_server.id == 1 %>
        <%= f.text_field :fqdn, class: 'form-control', readonly: true %>
      <% else %>
        <%= f.text_field :fqdn, class: 'form-control', required: true %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :username, class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_field :username, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_field :password, class: 'form-control', type: 'password', required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, t('zabbix_servers.details'), class: 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_area :details, class: 'form-control' %>
    </div>
  </div>
  <div class="form-actions-top">
    <%= f.submit nil, class: 'btn btn-primary create' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")), zabbix_servers_path, class: 'btn btn-default' %>
  </div>

<% end %>

app/views/zabbix_servers/edit.html.erb
<% provide(:title, I18n.t('zabbix_servers.zabbix')+" | "+I18n.t('helpers.titles.edit')) %>
<%- model_class = ZabbixServer -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/zabbix_servers/index.html.erb
<% provide(:title, I18n.t('zabbix_servers.zabbix')) %>
<%- model_class = ZabbixServer -%>
<div class="page-header">
  <h1><%= t 'zabbix_servers.zabbix' %></h1>
</div>


<!-- component template -->
<script id="grid-template" type="text/template"> <%= render 'vue/index' %> </script>

<!-- demo root element -->
<div id="indexElement" v-el:node>

  <div v-cloak>
    <div class="col-md-4"><input type="text" class="form-control" v-model="searchQuery" placeholder="<%= t 'infrastructures.search' %>"></div>

    <div class="pull-right">
      <a class="btn btn-danger btn-sm disabled"
      @click="delete_entry()"
      :class="{disabled: !can_delete()}">
          <%= fa 'times' %>
          <%= t 'common.btn.delete' %>
      </a>&nbsp
    </div>

    <div class="pull-right">
      <a class="btn btn-default btn-sm disabled"
          v-bind:href="picked.edit_zabbix_server_url"
          :class="{disabled: !can_edit()}">
          <span class='glyphicon glyphicon-edit'></span>
          <%= t 'helpers.links.edit' %>
      </a>&nbsp
    </div>
  </div>

  <demo-grid
  :data.sync="gridData"
  :columns="gridColumns"
  :filter-key="searchQuery"
  :picked.sync="picked"
  :index="index">
  </demo-grid>
</div>

<div  id="empty" style="display: none;"></div>
<span id="loading"><div class="loader"></div> <%= t 'common.msg.loading' %></span>
<hr>

<br>

<%= link_to(
  t('zabbix_servers.btn.add'),
  new_zabbix_server_path,
  class: 'btn btn-primary btn-sm'
) if current_user.admin? %>

app/views/zabbix_servers/new.html.erb
<% provide(:title, I18n.t('zabbix_servers.zabbix')+" | "+I18n.t('helpers.titles.new')) %>
<%- model_class = ZabbixServer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/zabbix_servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fqdn:</strong>
  <%= @zabbix_server.fqdn %>
</p>

<p>
  <strong>Username:</strong>
  <%= @zabbix_server.username %>
</p>

<p>
  <strong>Version:</strong>
  <%= @zabbix_server.version %>
</p>

<p>
  <strong>Details:</strong>
  <%= @zabbix_server.details %>
</p>

<%= link_to 'Edit', edit_zabbix_server_path(@zabbix_server) %> |
<%= link_to 'Back', zabbix_servers_path %>